### ISSUE TITLE
Tiles update bug

### ISSUE THREAD

**Issue by vyskocil** [route-me/route-me#105]
Sometimes when moving the map programmatically using moveToLatLong some tiles are not refreshed on screen, they stay displayed where new one should have been. The issue arise when the move is small.
It is very similar to the old bug 18 on google code project : http://code.google.com/p/route-me/issues/detail?id=18.
The sample TileIssue project demonstrate this issue.

**Comment by vyskocil** [comment]
I found when this bug was introduced in the project. 
It's the changes made to the method  -(void) removeTilesOutsideOf: (RMTileRect)rect in RMTileImageSet.m here :

https://github.com/route-me/route-me/commit/60f7d3fd719048faea6ba722dcb132320b57a070#MapView/Map/RMTileImageSet.m

I tried to put back the previous code for this method and now the TileIssue sample project works right !
This code was merged in August 11, 2010 by Foobaz for this issue : 

"Fixed issue with displaying tiles across international dateline. Also fixed bugs, made style more consistent, and added comments."
Is Foobaz still around ? Has someone ideas how to fix the bug without reverting the changes ?

**Comment by matspetter** [comment]
I can just confirm that by rolling back the RMTileImageSet::removeTilesOutsideOf method this particular problem goes away. I have had the problem consistently since i started to use route-me about 3-4 weeks ago. Unfortunately I cannot answer your question on how to roll it back but still keep the fix that Foobaz intended.

**Comment by incanus** [comment]
I have fixed this bug and am now resolving it against the rollback that was committed today. I'm able to bring back Foobaz's changes without the tile update bug. More soon.

**Comment by incanus** [comment]
Pull request to fix this here: https://github.com/route-me/route-me/pull/119
