### ISSUE TITLE
Make a new project in XCode 4

### ISSUE THREAD

**Issue by plaetzchen** [route-me/route-me#107]
Hi there,
I tried to follow the following guide (https://github.com/route-me/route-me/wiki/Embedding-Guide) to make use of the framework in my application. I managed to add the XCode Project to my project and I think I linked the libraries the right way but when I try to build the project the compilation projects stalls when prompting "Building Proj4". Can some one help me out with this?

Thanks. Philip

**Comment by vyskocil** [comment]
May you ask questions in the route-me mailing list and leave the bugtracking for opening bug, please.
