### ISSUE TITLE
unnecessary deprecation

### ISSUE THREAD

**Issue by incanus** [route-me/route-me#115]
I commented on an old, closed [pull request](https://github.com/route-me/route-me/pull/98#issuecomment-1024125) but adding it here for completion. 

That request deprecated `-[RMMarkerManager addMarker:AtLatLong:]`, causing warnings in existing codebases, when the pull request was meant to add better support for projected points and said "P.S. It isn't a refactoring, it is an addition."

**Comment by tracyharton** [comment]
Probably shouldn't deprecate a function without a replacement...
