### ISSUE TITLE
Marker label (UIView) Position

### ISSUE THREAD

**Issue by abdulmannanbutt** [route-me/route-me#129]
How can we set the position of a bubble which is a UIView. i am adding a marker in this way

UIImage *redMarkerImage = [UIImage imageNamed:@"red_pin.png" ];
RMMarker *newMarker = [[RMMarker alloc] initWithUIImage:redMarkerImage];

[newMarker setLabel:annotationView]; // where annotationView is a UIView like UIView \* annotation;

[self.mapView.contents.markerManager addMarker:newMarker AtLatLong:location];

when i run the app bubble appears in right side of the pin. But i want to set its location above the pin. please help ASAP...

**Comment by michaeltyson** [comment]
Hi - Probably best to send this to the mailing list (http://groups.google.com/group/route-me-map)
