### ISSUE TITLE
Smooth zooming similar to maps.app

### ISSUE THREAD

**Issue by michaeltyson** [route-me/route-me#15]
A patch was created, though it wasn't complete.

See:
http://groups.google.com/group/route-me-map/browse_thread/thread/ec93b8402c268d34

**Comment by servine** [comment]
I think the functionality for smooth zooming has already been applied.  Have you tried setting the tileDepth on RMMapContents?

Checkout http://groups.google.com/group/route-me-map/browse_thread/thread/8361e76ff1c84248/1f3054aa7c302d89?lnk=gst&q=patch+for+zoom

**Comment by michaeltyson** [comment]
It does seem to be zooming smoothly! I think this was just a legacy ticket that was never closed. Closing now.
