### ISSUE TITLE
libmapview.a not compiling for both armv6 & armv7

### ISSUE THREAD

**Issue by fabdelamora** [route-me/route-me#160]
Hey guys
for some reason I can't compile my project for it to be architecture armv6 & armv7 together.
The thing is that I was trying to upload my ios app to the app store and Apple didn't accepted my app because it was not built for armv6 architecture.

The error I get is the following:

////
ld: warning: ignoring file /temp/***/libMapView.a, file was built for archive which is not the architecture being linked (armv6)
Undefined symbols for architecture armv6:
"_pj_fwd", referenced from:
- [RMProjection latLongToPoint:] in libMapView.a(RMProjection.o)
  "pj_inv", referenced from:
- [RMProjection pointToLatLong:] in libMapView.a(RMProjection.o)
  "_pj_init_plus", referenced from:
- [RMProjection initWithString:InBounds:] in libMap.a(RMprojection.o)
  "_pj_free", referenced from:
- [RMProjection dealloc] in libMapView.a(RMProjection.o)
  ld:symbol(s) not found for architecture armv6
  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please HELPPPPPP!!!

**Comment by tracyharton** [comment]
Make sure proj4 is also building for armv6

**Comment by fabdelamora** [comment]
Thank you so much! That was exactly the problem!
