### ISSUE TITLE
libtool (libMapView.a error) on Simulator 3.1 build

### ISSUE THREAD

**Issue by michaeltyson** [route-me/route-me#28]
What steps will reproduce the problem?
1. Embed MapView in an XCode project made with Xcode v.3.0 [Checked that project builds and 
runs successfully on Simulator 2.2.1 and 3.0]
3. Upgrade SDK to XCode 3.1
4. Set up code signing required by v.3.1
5. Build with Simulator 3.1

What is the expected output? What do you see instead?
The expected output was a successful build, as in previous builds. 

Error received: Libtool "/Users/iphonedevel/Desktop/SpeedcamProject 
07.08/MapView/buid/Debug-iphonesimulator/libMapView.a" normal i386 (1 error)
/Developer/Platforms/iphoneSimulator.platform/Developer/usr/bin/libtool: -dynamic not 
specified the following flags are invalid: -ObjC
/Developer/Platforms/iphoneSimulator.platform/Developer/usr/bin/libtool: object /Developer/Platforms/iphoneSimulator.platform/Developer/SDKs/iPhoneSimulator3.1.sdk/usr/li
b/libsqlite3.dylib malformed object (unknown load command 5)

Command /Developer/Platforms/iphoneSimulator.platform/Developer/usr/bin/libtool failed with 
exit code 1

What subversion release are you using? Does the behavior occur on the
simulator, a real iPhone/iPod Touch, or both?
iphone SDK 3.1 beta 3. The behavior occurred on the simulator build.

If you can reproduce your bug, please provide the source code for a
reproducing case. The best place to start is with the SampleMap project.

I have reproduced the bug on the SampleMap project, but the code signing identity won't work
on another computer.
The only changes to the original SampleMap project were setting the code signing identity and 
the Info.plist bundle identifier to the info of the working certificate. The same error was 
encountered.

Please provide any additional information below.

This project has been tested extensively with the simulator on 2.2.1 and 3.0 but no actual 
device. Upgrade and compatibility to the 3.1 version was requested only recently but during the 
course of working with the route-me MapView project no embedding problems were 
encountered.

**Comment by amjaliks** [comment]
Issue outdated.
