### ISSUE TITLE
Drag and drop marker doesn't work on markers with small images

### ISSUE THREAD

**Issue by michaeltyson** [route-me/route-me#36]
What steps will reproduce the problem?
1. Add a marker
2. Set image to thin image (4-5 pixels)
3. Try to drag it horizonatally and with speed a little bit above normal.

What is the expected output? 

Marker should be dragged smoothly all the way from one point to another.

What do you see instead?

Marker is dragged for a short distance and after that it is dropped and map 
scrolls instead

What subversion release are you using? Does the behavior occur on the
simulator, a real iPhone/iPod Touch, or both?

0.5, it happens both on the device and simulator.

It seems to be a problem of how touches are handled. Right now, when 
touch moves, route-me checks if there is a marker layer on new position. If 
there is something - corresponding marker is notified about move.

And when we have a thin or short image - delta between previous position 
and current position can be bigger than corresponding image dimension. 
So route-me doesn't find any marker on the new position and doesn't 
notify marker about move.

I expect, it should handle drag'n'drop absolutely separately and then d'n'd 
started it should remember marker on which it started and move it until 
touch cancel/touch exit occurs or until any other touch detected.

**Comment by michaeltyson** [comment]
This occurs as the marker itself is handling the drag, and the touch exists the bounds of the view during faster drags.

The solution is to implement marker dragging in the superview.  This will happen as part of the planned refactoring of Route Me.

**Comment by saimonx** [comment]
How can i do that? Sorry, i am not an expert on Objetive-c.

Thanks!

**Comment by michaeltyson** [comment]
I'm afraid this is a longer-term issue - redevelopment of the dragging code will take a little while.

As a shorter-term workaround, you could try using a larger (but transparent) marker surface.

**Comment by saimonx** [comment]
ok, i will try it.

Thanks!!

**Comment by saimonx** [comment]
any new about it?
