### ISSUE TITLE
SimpleMap example doesnt compile under 3.1.2

### ISSUE THREAD

**Issue by michaeltyson** [route-me/route-me#39]
What steps will reproduce the problem?
1.load simple map example 
2.try to compile it with iphone sdk 3.1.2
3.error

What is the expected output? What do you see instead?

> see screenshot

What subversion release are you using? Does the behavior occur on the
simulator, a real iPhone/iPod Touch, or both?

verion 0.5

Thanks

**Comment by vyskocil** [comment]
Route-me version 0.5 is very old and deprecated.
