### ISSUE TITLE
Double clicking on map doesn't go to the next zoom level

### ISSUE THREAD

**Issue by michaeltyson** [route-me/route-me#44]
What steps will reproduce the problem?
1. Start SampleMap application, and note the current zoom level shown on 
screen e.g. 15 
2. Double click on map
3. Zoom level after zooming is not a native zoom level e.g. it goes from 15 
to 16.20

What is the expected output?
Map should zoom exactly to the current zoom level + 1.

What subversion release are you using? 
r612

Does the behavior occur on the simulator, a real iPhone/iPod Touch, or 
both?
Both

I have managed to circumvent this by modifying animatedZoomStep to 
never exceed the targetZoom:
- (void)animatedZoomStep:(NSTimer *)timer
  {
  
  ```
  .....
  ```
  
  if ((zoomIncr > 0 && [self zoom] >= targetZoom) || (zoomIncr < 0 && 
  [self zoom] <= targetZoom))
  { 
             ...
  }
  else
  {
      if (([self zoom] + zoomIncr) > targetZoom) {
          zoomIncr = targetZoom - [self zoom];
      }
      float zoomFactorStep = exp2f(zoomIncr);
  
  ```
          ......
  ```
  
  }
  }

However I still don't understand the root of the problem i.e. why the 
parameters passed to animatedZoomStep cause it to overstep the 
targetZoom.

**Comment by michaeltyson** [comment]
This is occurring due to a dodgy zoom animation implementation, which repeatedly zooms in by a precalculated increment, but does so inconsistently.

See RMMapContents' animatedZoomStep

**Comment by vyskocil** [comment]
Fixed now.
