### ISSUE TITLE
Unable to build to device in SDK 4

### ISSUE THREAD

**Issue by michaeltyson** [route-me/route-me#47]
What steps will reproduce the problem?
1. Compiling application with target as device.
2. Compilation fails with error message of duplicate symbol _aasin

What is the expected output? It should compile 
What do you see instead? Error message  duplicate symbol _aasin

What subversion release are you using? Does the behavior occur on the
simulator, a real iPhone/iPod Touch, or both?
Only when compiling to the device. If you compile to the simulator it works fine.

It occurs only with the SDK 4 compiler. The previous compiler ( 3.1.3) builds fine.

**Comment by michaeltyson** [comment]
See [discussion](http://code.google.com/p/route-me/issues/detail?id=138).  Is this still a problem? Works for me.

**Comment by amjaliks** [comment]
Issue outdated.
Everything works fine. Even with more modern 4.3.
