### ISSUE TITLE
Is there any way to implement the callout bubble when tabbing a marker just like MKMapView?

### ISSUE THREAD

**Issue by michaeltyson** [route-me/route-me#53]
Is there any way to implement the callout bubble when tabbing a marker just like MKMapView? 
With transparent, a round button right side, title and subtitle, and some animations.

**Comment by michaeltyson** [comment]
Not a bugreport

**Comment by horseshoe7** [comment]
Bug or no bug, how does one do this?  It isn't clear whether this has been fixed.  The code I'm using (via download instructions from CloudMade) doesn't handle touches on the RMMarker.label 's subviews.  This prevents callout bubbles being useful.
