### ISSUE TITLE
Marker radius display

### ISSUE THREAD

**Issue by michaeltyson** [route-me/route-me#8]
Two possible approaches:

(a) Direct drawing of a filled ellipse, or
(b) Introduce dependence on RMPath

**Comment by hjon** [comment]
I'm not clear what you mean by this. Are you imagining something similar to what Maps.app does with the user location dot, which indicates the current accuracy? Or something different?

**Comment by michaeltyson** [comment]
This does seem vague - I suggest closing this issue and calling it orphaned. (original issue and discussion [here](http://code.google.com/p/route-me/issues/detail?id=60&colspec=ID%20Type%20Status%20Reporter%20Opened%20Modified%20Owner%20Summary%20Milestone); I'm not sure this should be something we devote resources to at this stage.  It's pretty easy to implement a custom marker to draw radii - I did this in my own project to mimic the MapKit user location gem, and it look about 20 minutes.

**Comment by vyskocil** [comment]
I agree, but concerning RMPath it think it needs some (re)works : redraw is sometimes broken, slowdowns with small zoom level, out of memory error arise sometimes (layer too big),missing features,... I understood it is was a very preliminary and rough implementation...

**Comment by michaeltyson** [comment]
Indeed, it's pretty rough. I've created #64 for this one, but will close this ticket here
