### ISSUE TITLE
How should I submit changes for review?

### ISSUE THREAD

**Issue by CmputrAce** [route-me/route-me#85]
I'm writing an app using route-me, and have been able to add some code extensions using categories, but I have also needed to change some "core" code to enable the features that I need for the app. I think you will be interested in these changes but definitely need to review them. How should I accomplish this? 

The majority of changes are in how it handles gestures - I've just added more delegate methods to allow the parent app to respond to more gestures than are currently delegated. I haven't added any more gesture recognition code, however. It's just added lines of code.

Jim

**Comment by michaeltyson** [comment]
Cheers, Jim.  To do this, click the "Pull Request" button, which will open an issue in the tracker that is linked to your changes.
