### ISSUE TITLE
Sometimes RMMapView sticks at one zoom level

### ISSUE THREAD

**Issue by amjaliks** [route-me/route-me#89]
Sometimes RMMapView sticks at one zoom level and ignores any try to change zoom with pinch.

**Comment by hjon** [comment]
I have some fixes for similar issues and will try to submit them sometime this weekend to see if they fix what you experienced.

**Comment by amjaliks** [comment]
Do you know how to reproduce this bug? Currently I know only that it happens, but without ways to definitely reproduce it.

**Comment by hjon** [comment]
I've experienced it when trying to limit the zoom levels of the map. If you were zoomed all the way in or all the way out, it could get stuck. The map wasn't properly clamping the zoom to be within the min and max zoom levels, so my code makes sure the zoom level was properly clamped.

Does that seem to match what you saw?

**Comment by hjon** [comment]
I've added a pull request to fix this issue here: https://github.com/route-me/route-me/pull/91

**Comment by amjaliks** [comment]
Last time map view really stuck, when it was at max zoom. But it happens only sometimes, I don't know exactly how to reproduce it.

I will apply patch to my fork. And we will see, would it help also in my case.

**Comment by amjaliks** [comment]
Looks like #91 doesn't solve my issue. My map stuck once again. :(

**Comment by amjaliks** [comment]
I found, that need to tweak one more line, to solve my issue. For more details: https://github.com/hjon/route-me/commit/b9de0ca40e035821acd5f843537ce74346f8e13a#L1R293

I think it will be better, if Jon will edit this line and add a new commit to his pull request, thus, I don't need to create a new pull request by myself.

**Comment by hjon** [comment]
Sure thing, I'll take a look and add a new pull request.
